development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://kytmgfmqgxrhhv:a61fa274cf0c9881b35731238975eb31c1a0efc543a99f283cde002b3439cc47@ec2-107-21-248-129.compute-1.amazonaws.com:5432/dcupabo86gjf4e
